### ISSUE TITLE
KeyError: 'Domain' when retraining model 

### ISSUE THREAD

**Issue by leebean337** [MarvinLvn/voice-type-classifier#10]
When attempting to retrain the model on our data, we're getting the following error:
```
(pyannote) leemoore@ip-172-31-9-0:~/projects/voice-type-classifier$ pyannote-audio mlt train --subset=train --to=50 --from=100 --parallel=4 model/ ELLIS.SpeakerDiarization.Classroom                                                                                                                                                     
Training set: 10it [01:34,  9.46s/it]                                                 
Traceback (most recent call last):                                                   
  File "/opt/miniconda3/envs/pyannote/bin/pyannote-audio", line 8, in <module>        
    sys.exit(main())                                                               
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/applications/pyannote_audio.py", line 376, in main                                         
    app.train(protocol, **params)                                                     
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/applications/base.py", line 225, in train                                                  
    for _ in iterations:                                                              
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/train/trainer.py", line 329, in fit_iter                                                   
    self.optimizer_ = get_optimizer(self.parameters(), lr=lr)                         
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/train/trainer.py", line 166, in parameters                                                 
    return chain(self.model_.parameters(), self.more_parameters())                    
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/labeling/tasks/labels_detection.py", line 387, in more_parameters                          
    n_classes = len(self.specifications[self.domain]['classes'])                      
KeyError: 'domain'    
```
We are using the following database.yml file and configured the .lst, .rttm, and .uem accordingly to the specifications provided (and our labels in the .rttm file are strictly FEM/MAL/CHI/KCHI). We have made no alternations to the [config.yml](https://github.com/MarvinLvn/voice-type-classifier/blob/new_model/model/config.yml)
```
Databases:
   ELLIS: /home/leemoore/projects/data/ellis/{uri}.wav

Protocols:
   ELLIS:
      SpeakerDiarization:
         Classroom:
           train:
              uri: /home/leemoore/projects/data/ellis/ellis.trn.lst
              annotation: /home/leemoore/projects/data/ellis/ellis.trn.rttm
              annotated: /home/leemoore/projects/data/ellis/ellis.trn.uem
           development:
              uri: /home/leemoore/projects/data/ellis/ellis.dev.lst
              annotation: /home/leemoore/projects/data/ellis/ellis.dev.rttm
              annotated: /home/leemoore/projects/data/ellis/ellis.dev.uem
           test:
              uri: /home/leemoore/projects/data/ellis/ellis.tst.lst
              annotation: /home/leemoore/projects/data/ellis/ellis.tst.rttm
              annotated: /home/leemoore/projects/data/ellis/ellis.tst.uem
```
The train .lst file looks like this:
```
e6001_000000
e6002_080126
e6003_080125
e6009_080211
e6009_080217
e6010_080127
e6011_080127
e6012_080127
e6013_080127
e6014_080127
```

**Comment by MarvinLvn** [comment]
The error probably comes from the Task specification.
In the `config.yml`, could you try replacing :

```
task:
  params:
    alpha: 0
    duration: 2.0
    domain: domain
    batch_size: 64
    attachment: 0
    per_epoch: 1
    domain_loss: MSELoss
    rnn:
      unit: LSTM
      hidden_size: 128
      num_layers: 1
      bidirectional: False
      pool: max
    labels_spec:
      regular: ['KCHI', 'CHI', 'MAL', 'FEM']
      union:
        SPEECH: ['KCHI', 'CHI', 'FEM', 'MAL', 'SPEECH']
  name: DomainAdversarialMultilabelDetection
```

by

```
task:
  params:
    duration: 2.0
    batch_size: 64
    per_epoch: 1
    labels_spec:
      regular: ['KCHI', 'CHI', 'MAL', 'FEM']
      union:
        SPEECH: ['KCHI', 'CHI', 'FEM', 'MAL', 'SPEECH']
  name: MultilabelDetection
```

It should solve the issue !
Let me know if it works please :)

PS : For more information, `pyannote` is expecting a `domain` key to train the model adversarially w.r.t the domain information such as in [here](https://arxiv.org/abs/1910.10655). The weight associated to the domain loss being 0 in this case, it is strictly equivalent than not considering at all this domain adversarial loss.

**Comment by MarvinLvn** [comment]
I've decided to update the `config.yml` in the repo directly to make the model retrainable more easily.
I'm waiting for your feedback before closing the issue :)

**Comment by leebean337** [comment]
This worked, thank you! Actually it resolved the first issue and then I experienced ```RuntimeError: CUDA out of memory``` errors. By changing the Batch Size=32, this resolve and it seems to be retaining now.

**Comment by leebean337** [comment]
Training completed successfully (we think). However, I cannot run the validate step - will open a new issue.
