### ISSUE TITLE
./apply.sh does not work for numeric uris

### ISSUE THREAD

**Issue by leebean337** [MarvinLvn/voice-type-classifier#11]
When attempting to apply the vtc model on a wav file which is named using only numerals and underscores (i.e. 6001_000000.wav), the prediction fails with a KeyError and ValueError. Resolved when adding an alphabetical character to the beginning of the file name.
```
(pyannote) leemoore@ip-172-31-9-0:~/voice_type_classifier$ ./apply.sh 6001_000000.wav
Creating config for pyannote.
Done creating config for pyannote.
Traceback (most recent call last):
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/database/__init__.py", line 107, in get_database
    database = DATABASES[database_name]
KeyError: '6001_000000'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/pyannote/bin/pyannote-audio", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/applications/pyannote_audio.py", line 452,in main
    Application.apply_pretrained(validate_dir, protocol, **params)
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/applications/labels_detection.py", line 450, in apply_pretrained
    preprocessors=preprocessors)
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/database/__init__.py", line 151, in get_protocol
    **kwargs)
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/database/__init__.py", line 124, in get_database
    raise ValueError(msg)
ValueError: Could not find any protocol for "6001_000000" database. Please refer to pyannote.database documentation to learn how to define them: https://github.com/pyannote/pyannote-database
Something went wrong when applying the model
Aborting.
```
This now works with a different file name:
```
(pyannote) leemoore@ip-172-31-9-0:~/voice_type_classifier$ mv 6001_000000.wav e6001_000000.wav
(pyannote) leemoore@ip-172-31-9-0:~/voice_type_classifier$ ./apply.sh e6001_000000.wav
Creating config for pyannote.     Done creating config for pyannote. 
Test set: 1it [00:32, 32.62s/it]       Test set: 1it [00:00,  3.64it/s]
Test set: 1it [00:00,  3.68it/s]        Test set: 1it [00:00,  3.68it/s]
Test set: 1it [00:00,  3.69it/s]        Test set: 1it [00:00,  3.72it/s]
Took 39 sec on e6001_000000.
--
```

**Comment by MarvinLvn** [comment]
Fixed in commit 9351cafb09a737c6ef47d235e3caf9e4685a1b5f
After having pulled the repository, you shouldn't encounter this error anymore.
Closing the issue.
