### ISSUE TITLE
np.long issue

### ISSUE THREAD

**Issue by giodesp** [MarvinLvn/voice-type-classifier#25]
Hi,
I am running the VTC in googlecolab, using a conda environment loaded from vtc.yml as in the installation guide, and running into an issue with a deprecated np.long type:
"AttributeError: module 'numpy' has no attribute 'long'".
I will post the entire output below. If anyone has a solution for me, I would really appreciate it. Thank you.

Creating config for pyannote.
Done creating config for pyannote.
/usr/local/lib/python3.8/site-packages/numba/types/__init__.py:110: FutureWarning: In the future `np.long` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  long_ = _make_signed(np.long)
Traceback (most recent call last):
  File "/usr/local/bin/pyannote-audio", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/pyannote/audio/applications/pyannote_audio.py", line 307, in main
    from .labels_detection import MultilabelDetection
  File "/usr/local/lib/python3.8/site-packages/pyannote/audio/applications/labels_detection.py", line 39, in <module>
    from pyannote.audio.applications.base import create_zip
  File "/usr/local/lib/python3.8/site-packages/pyannote/audio/applications/base.py", line 46, in <module>
    from pyannote.audio.features.utils import get_audio_duration
  File "/usr/local/lib/python3.8/site-packages/pyannote/audio/features/__init__.py", line 33, in <module>
    from .base import FeatureExtraction
  File "/usr/local/lib/python3.8/site-packages/pyannote/audio/features/base.py", line 32, in <module>
    from .utils import RawAudio
  File "/usr/local/lib/python3.8/site-packages/pyannote/audio/features/utils.py", line 32, in <module>
    import librosa
  File "/usr/local/lib/python3.8/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/usr/local/lib/python3.8/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.8/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/usr/local/lib/python3.8/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/usr/local/lib/python3.8/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.8/site-packages/librosa/util/utils.py", line 9, in <module>
    import numba
  File "/usr/local/lib/python3.8/site-packages/numba/__init__.py", line 15, in <module>
    from . import config, errors, _runtests as runtests, types
  File "/usr/local/lib/python3.8/site-packages/numba/types/__init__.py", line 110, in <module>
    long_ = _make_signed(np.long)
  File "/usr/local/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'long'
Something went wrong when applying the model
Aborting.

**Comment by giodesp** [comment]
I will leave this here in case it is useful for anyone but the issue seems to arise from numpy having received an update on Dec 18 (1.24.0) which no longer recognised the 'long' variable type. Reverting back to numpy 1.23.5 seems to have fixed this issue.
