### ISSUE TITLE
Issue when applying model

### ISSUE THREAD

**Issue by shibess** [MarvinLvn/voice-type-classifier#29]
<img width="794" alt="Screen Shot 2023-06-12 at 11 50 44 AM" src="https://github.com/MarvinLvn/voice-type-classifier/assets/35199097/4d171a43-45a6-48cb-bd9a-fe8a752b75b9">

*Hello!* 
I am having an issue applying the model to the given audio file. I have been looking through the other issues and could not find a solution. Above is what happens when I try to run the model on an audio file. The word "dominic" at the end of the line I think is just a quirk of apple that can't be changed (though is this is the issue I also do not know how to fix it.) 

Thanks in Advance

**Comment by MarvinLvn** [comment]
Hi, 

Could you please give me the output of `ls /Users/dominic/Desktop/ISL/box_audio` ?

Thanks a lot!

**Comment by shibess** [comment]
<img width="705" alt="Screen Shot 2023-06-14 at 11 04 41 AM" src="https://github.com/MarvinLvn/voice-type-classifier/assets/35199097/87b057ea-cc5f-42d8-b9c3-c555bffd566c">

This is what I get! Thanks!

**Comment by MarvinLvn** [comment]
Apologies for the delay in addressing your issues! I must say I'm not really inspired by the error message.
I have just attempted a fresh install of the repo, and the code works fine.

From what I can tell, it seems `pyannote.audio` has not been correctly installed. 
The code complains that the call to the `pyannote-audio` command is wrong (it does not do so on a fresh install on my Fedora system).

Could you give me the output of `pyannote-audio --version` command (don't forget to activate the pyannote conda env)?
In the meantime, are you sure you followed [the installation instructions](https://github.com/MarvinLvn/voice-type-classifier/blob/new_model/docs/installation.md)? 

That would be amazing if you could: 1) attempt a fresh install of the repo; and 2) give me the output of the installation instructions
This way I'd be able to tell if something went wrong!

**Comment by shibess** [comment]
I tried doing a fresh install of the repo to no avail. There was a path error when trying to install pyannote-audio that I found when installing! Hopefully this will help you find out what's causing the error, screenshot attached.
<img width="564" alt="Screen Shot 2023-06-19 at 12 28 56 PM" src="https://github.com/MarvinLvn/voice-type-classifier/assets/35199097/4e5ba765-7810-410f-bc55-56363b2dfd57">

Thanks for all your help!

**Comment by MarvinLvn** [comment]
Hi! 

This is very helpful, thanks!
I don't see any error in the attached screenshot. The command first clones the `voice_type_classifier` repo, and then the `pyannote-audio` repo which is the expected behavior of `git clone --recurse-submodules`.

The screenshot shows that `pyannote-audio` was still being cloned. Please make sure you wait until the command is done (this can take a bit). 

Could you please give me the output of `conda env create -f vtc.yml` or attach a screenshot with the error you mentioned? 

Thanks a lot!

**Comment by shibess** [comment]
```shell
Downloading and Extracting Packages
                                                                                
Preparing transaction: done                                                     
Verifying transaction: done                                                     
Executing transaction: done                                                     
Installing pip dependencies: / Ran pip subprocess with arguments:
['/Users/dominic/anaconda3/envs/pyannote/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Users/dominic/Desktop/GitHub/voice_type_classifier/condaenv.9bw_hxs6.requirements.txt', '--exists-action=b']
Pip subprocess output:
Processing ./pyannote-audio
Collecting numpy==1.23.5
  Using cached numpy-1.23.5-cp38-cp38-macosx_11_0_arm64.whl (13.3 MB)
Collecting cachetools>=2.0.0
  Using cached cachetools-5.3.1-py3-none-any.whl (9.3 kB)
Collecting librosa
  Using cached librosa-0.10.0.post2-py3-none-any.whl (253 kB)
Collecting pandas>=0.18.0
  Using cached pandas-2.0.2-cp38-cp38-macosx_11_0_arm64.whl (10.7 MB)
Collecting pyannote.core==3.7.1
  Using cached pyannote.core-3.7.1-py3-none-any.whl (54 kB)
Collecting pyannote.database==3.0.1
  Using cached pyannote.database-3.0.1-py3-none-any.whl (32 kB)
Collecting pyannote.pipeline==1.5
  Using cached pyannote.pipeline-1.5-py3-none-any.whl (24 kB)
Collecting pyYAML>=3.12
  Using cached PyYAML-6.0-cp38-cp38-macosx_11_0_arm64.whl
Collecting scikit-learn>=0.20.2
  Using cached scikit_learn-1.2.2-cp38-cp38-macosx_12_0_arm64.whl (8.3 MB)
Collecting sortedcollections>=1.0.1
  Using cached sortedcollections-2.1.0-py3-none-any.whl (9.5 kB)
Collecting sortedcontainers>=2.0.4
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting soundfile>=0.10.2
  Using cached soundfile-0.12.1-py2.py3-none-macosx_11_0_arm64.whl (1.1 MB)
Collecting tqdm>=4.29.1
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting tensorboard>=2.0.0
  Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
Collecting typing_extensions>=3.7.4
  Using cached typing_extensions-4.6.3-py3-none-any.whl (31 kB)
Collecting pescador>=2.1.0
  Using cached pescador-2.1.0-py3-none-any.whl
Collecting Pillow>=6.2.1
  Using cached Pillow-9.5.0-cp38-cp38-macosx_11_0_arm64.whl (3.1 MB)
Collecting torch>=1.4.0
  Using cached torch-2.0.1-cp38-none-macosx_11_0_arm64.whl (55.8 MB)
Collecting numba
  Using cached numba-0.57.0-cp38-cp38-macosx_11_0_arm64.whl (2.5 MB)
  Using cached numba-0.48.0.tar.gz (2.0 MB)
Collecting simplejson>=3.8.1
  Using cached simplejson-3.19.1-cp38-cp38-macosx_11_0_arm64.whl (74 kB)
Collecting matplotlib>=2.0.0
  Using cached matplotlib-3.7.1-cp38-cp38-macosx_11_0_arm64.whl (7.3 MB)
Collecting scipy>=1.1
  Using cached scipy-1.10.1-cp38-cp38-macosx_12_0_arm64.whl (28.8 MB)
Collecting optuna>=1.2
  Using cached optuna-3.2.0-py3-none-any.whl (390 kB)
Collecting docopt>=0.6.2
  Using cached docopt-0.6.2-py2.py3-none-any.whl
Collecting filelock>=3.0.10
  Using cached filelock-3.12.2-py3-none-any.whl (10 kB)
Collecting llvmlite<0.32.0,>=0.31.0dev0
  Using cached llvmlite-0.31.0.tar.gz (110 kB)
Requirement already satisfied: setuptools in /Users/dominic/anaconda3/envs/pyannote/lib/python3.8/site-packages (from numba->-r /Users/dominic/Desktop/GitHub/voice_type_classifier/condaenv.9bw_hxs6.requirements.txt (line 19)) (67.7.2)
Collecting lazy-loader>=0.1
  Using cached lazy_loader-0.2-py3-none-any.whl (8.6 kB)
Collecting joblib>=0.14
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Collecting soxr>=0.3.2
  Using cached soxr-0.3.5-cp38-cp38-macosx_11_0_arm64.whl (380 kB)
Collecting msgpack>=1.0
  Using cached msgpack-1.0.5-cp38-cp38-macosx_11_0_arm64.whl (68 kB)
Collecting decorator>=4.3.0
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting pooch<1.7,>=1.0
  Using cached pooch-1.6.0-py3-none-any.whl (56 kB)
Collecting librosa
  Using cached librosa-0.10.0.post1-py3-none-any.whl (252 kB)
Collecting pooch>=1.0
  Using cached pooch-1.7.0-py3-none-any.whl (60 kB)
Collecting librosa
  Using cached librosa-0.10.0-py3-none-any.whl (252 kB)
  Using cached librosa-0.9.2-py3-none-any.whl (214 kB)
Collecting resampy>=0.2.2
  Using cached resampy-0.4.2-py3-none-any.whl (3.1 MB)
Collecting packaging>=20.0
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting audioread>=2.1.9
  Using cached audioread-3.0.0-py3-none-any.whl
Collecting python-dateutil>=2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytz>=2020.1
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
Collecting tzdata>=2022.1
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting cffi>=1.0
  Using cached cffi-1.15.1-cp38-cp38-macosx_11_0_arm64.whl
Collecting werkzeug>=1.0.1
  Using cached Werkzeug-2.3.6-py3-none-any.whl (242 kB)
Collecting grpcio>=1.48.2
  Using cached grpcio-1.54.2-cp38-cp38-macosx_10_10_universal2.whl (8.7 MB)
Collecting tensorboard-data-server<0.8.0,>=0.7.0
  Downloading tensorboard_data_server-0.7.1-py3-none-any.whl (2.4 kB)
Collecting markdown>=2.6.8
  Using cached Markdown-3.4.3-py3-none-any.whl (93 kB)
Collecting absl-py>=0.4
  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)
Collecting google-auth-oauthlib<1.1,>=0.5
  Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Collecting google-auth<3,>=1.6.3
  Using cached google_auth-2.20.0-py2.py3-none-any.whl (181 kB)
Collecting requests<3,>=2.21.0
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting protobuf>=3.19.6
  Downloading protobuf-4.23.3-cp37-abi3-macosx_10_9_universal2.whl (400 kB)
Requirement already satisfied: wheel>=0.26 in /Users/dominic/anaconda3/envs/pyannote/lib/python3.8/site-packages (from tensorboard>=2.0.0->-r /Users/dominic/Desktop/GitHub/voice_type_classifier/condaenv.9bw_hxs6.requirements.txt (line 14)) (0.40.0)
Collecting six>=1.8
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pyzmq>=15.0
  Using cached pyzmq-25.1.0-cp38-cp38-macosx_10_15_universal2.whl (1.8 MB)
Collecting sympy
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting networkx
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting rsa<5,>=3.1.4
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
Collecting urllib3<2.0
  Using cached urllib3-1.26.16-py2.py3-none-any.whl (143 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting importlib-metadata>=4.4
  Using cached importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
Collecting zipp>=0.5
  Using cached zipp-3.15.0-py3-none-any.whl (6.8 kB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting contourpy>=1.0.1
  Downloading contourpy-1.1.0-cp38-cp38-macosx_11_0_arm64.whl (229 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.4.4-cp38-cp38-macosx_11_0_arm64.whl (63 kB)
Collecting pyparsing>=2.3.1
  Using cached pyparsing-3.1.0-py3-none-any.whl (102 kB)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.40.0-cp38-cp38-macosx_10_9_universal2.whl (2.6 MB)
Collecting importlib-resources>=3.2.0
  Using cached importlib_resources-5.12.0-py3-none-any.whl (36 kB)
Collecting cmaes>=0.9.1
  Using cached cmaes-0.9.1-py3-none-any.whl (21 kB)
Collecting alembic>=1.5.0
  Using cached alembic-1.11.1-py3-none-any.whl (224 kB)
Collecting colorlog
  Using cached colorlog-6.7.0-py2.py3-none-any.whl (11 kB)
Collecting sqlalchemy>=1.3.0
  Downloading SQLAlchemy-2.0.16-cp38-cp38-macosx_11_0_arm64.whl (2.0 MB)
Collecting Mako
  Using cached Mako-1.2.4-py3-none-any.whl (78 kB)
Collecting platformdirs>=2.5.0
  Downloading platformdirs-3.6.0-py3-none-any.whl (16 kB)
Collecting pyasn1<0.6.0,>=0.4.6
  Using cached pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-cp38-cp38-macosx_11_0_arm64.whl (121 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
Collecting resampy>=0.2.2
  Using cached resampy-0.4.1-py3-none-any.whl (3.1 MB)
  Using cached resampy-0.4.0-py3-none-any.whl (3.1 MB)
  Using cached resampy-0.3.1-py3-none-any.whl (3.1 MB)
Collecting MarkupSafe>=2.1.1
  Using cached MarkupSafe-2.1.3-cp38-cp38-macosx_10_9_universal2.whl (17 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Building wheels for collected packages: pyannote.audio, numba, llvmlite
  Building wheel for pyannote.audio (setup.py): started
  Building wheel for pyannote.audio (setup.py): finished with status 'done'
  Created wheel for pyannote.audio: filename=pyannote.audio-0+unknown-py3-none-any.whl size=220488 sha256=8551535cf3dd370896637e790c9063d9ed122fc2583e35481bfd0ce21652b4e9
  Stored in directory: /Users/dominic/Library/Caches/pip/wheels/27/14/6c/a34dea60929fa760f364239320ed21a65b2dc3842c01af62c7
  Building wheel for numba (setup.py): started
  Building wheel for numba (setup.py): finished with status 'error'
  Running setup.py clean for numba
  Building wheel for llvmlite (setup.py): started
  Building wheel for llvmlite (setup.py): finished with status 'error'
  Running setup.py clean for llvmlite
Successfully built pyannote.audio
Failed to build numba llvmlite
Installing collected packages: zipp, six, numpy, urllib3, tzdata, typing-extensions, pytz, python-dateutil, pyparsing, pyasn1, Pillow, packaging, MarkupSafe, kiwisolver, importlib-resources, idna, fonttools, cycler, contourpy, charset-normalizer, certifi, sqlalchemy, sortedcontainers, simplejson, scipy, rsa, requests, pycparser, pyasn1-modules, pandas, oauthlib, matplotlib, Mako, llvmlite, importlib-metadata, cachetools, tqdm, threadpoolctl, requests-oauthlib, pyYAML, pyannote.core, platformdirs, numba, mpmath, joblib, google-auth, colorlog, cmaes, cffi, alembic, werkzeug, tensorboard-data-server, sympy, soundfile, scikit-learn, resampy, pyzmq, pyannote.database, protobuf, pooch, optuna, networkx, markdown, jinja2, grpcio, google-auth-oauthlib, filelock, docopt, decorator, audioread, absl-py, torch, tensorboard, sortedcollections, pyannote.pipeline, pescador, librosa, pyannote.audio
    Running setup.py install for llvmlite: started
    Running setup.py install for llvmlite: finished with status 'error'

Pip subprocess error:
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  ERROR: Command errored out with exit status 1:
   command: /Users/dominic/anaconda3/envs/pyannote/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/numba_ea00c6e5808c47a992d49d8b7b85630d/setup.py'"'"'; __file__='"'"'/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/numba_ea00c6e5808c47a992d49d8b7b85630d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-wheel-o_xh1p52
       cwd: /private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/numba_ea00c6e5808c47a992d49d8b7b85630d/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/numba_ea00c6e5808c47a992d49d8b7b85630d/setup.py", line 358, in <module>
      metadata['ext_modules'] = get_ext_modules()
    File "/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/numba_ea00c6e5808c47a992d49d8b7b85630d/setup.py", line 98, in get_ext_modules
      import numpy.distutils.misc_util as np_misc
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
  ERROR: Failed building wheel for numba
  ERROR: Command errored out with exit status 1:
   command: /Users/dominic/anaconda3/envs/pyannote/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/numba_ea00c6e5808c47a992d49d8b7b85630d/setup.py'"'"'; __file__='"'"'/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/numba_ea00c6e5808c47a992d49d8b7b85630d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/numba_ea00c6e5808c47a992d49d8b7b85630d
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/numba_ea00c6e5808c47a992d49d8b7b85630d/setup.py", line 358, in <module>
      metadata['ext_modules'] = get_ext_modules()
    File "/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/numba_ea00c6e5808c47a992d49d8b7b85630d/setup.py", line 98, in get_ext_modules
      import numpy.distutils.misc_util as np_misc
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
  ERROR: Failed cleaning build dir for numba
  ERROR: Command errored out with exit status 1:
   command: /Users/dominic/anaconda3/envs/pyannote/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/setup.py'"'"'; __file__='"'"'/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-wheel-zy7rugib
       cwd: /private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/
  Complete output (36 lines):
  /Users/dominic/anaconda3/envs/pyannote/lib/python3.8/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
  !!
  
          ********************************************************************************
          Requirements should be satisfied by a PEP 517 installer.
          If you are using pip, you can try `pip install --use-pep517`.
          ********************************************************************************
  
  !!
    dist.fetch_build_eggs(dist.setup_requires)
  running bdist_wheel
  /Users/dominic/anaconda3/envs/pyannote/bin/python /private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/Users/dominic/anaconda3/envs/pyannote/lib/python3.8/subprocess.py", line 415, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/Users/dominic/anaconda3/envs/pyannote/lib/python3.8/subprocess.py", line 493, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/Users/dominic/anaconda3/envs/pyannote/lib/python3.8/subprocess.py", line 858, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/Users/dominic/anaconda3/envs/pyannote/lib/python3.8/subprocess.py", line 1720, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/ffi/build.py", line 168, in <module>
      main()
    File "/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/ffi/build.py", line 162, in main
      main_posix('osx', '.dylib')
    File "/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/ffi/build.py", line 107, in main_posix
      raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/Users/dominic/anaconda3/envs/pyannote/bin/python' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
    ERROR: Command errored out with exit status 1:
     command: /Users/dominic/anaconda3/envs/pyannote/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/setup.py'"'"'; __file__='"'"'/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-record-q29lze81/install-record.txt --single-version-externally-managed --compile --install-headers /Users/dominic/anaconda3/envs/pyannote/include/python3.8/llvmlite
         cwd: /private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/
    Complete output (52 lines):
    /Users/dominic/anaconda3/envs/pyannote/lib/python3.8/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
    !!
    
            ********************************************************************************
            Requirements should be satisfied by a PEP 517 installer.
            If you are using pip, you can try `pip install --use-pep517`.
            ********************************************************************************
    
    !!
      dist.fetch_build_eggs(dist.setup_requires)
    running install
    /Users/dominic/anaconda3/envs/pyannote/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer, pypa/build or
            other standards-based tools.
    
            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************
    
    !!
      self.initialize_options()
    running build
    got version from file /private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/llvmlite/_version.py {'version': '0.31.0', 'full': 'fe7d985f6421d87f613bd414479d29d912771562'}
    running build_ext
    /Users/dominic/anaconda3/envs/pyannote/bin/python /private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/Users/dominic/anaconda3/envs/pyannote/lib/python3.8/subprocess.py", line 415, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/Users/dominic/anaconda3/envs/pyannote/lib/python3.8/subprocess.py", line 493, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Users/dominic/anaconda3/envs/pyannote/lib/python3.8/subprocess.py", line 858, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/Users/dominic/anaconda3/envs/pyannote/lib/python3.8/subprocess.py", line 1720, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/ffi/build.py", line 168, in <module>
        main()
      File "/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/ffi/build.py", line 162, in main
        main_posix('osx', '.dylib')
      File "/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/Users/dominic/anaconda3/envs/pyannote/bin/python' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/dominic/anaconda3/envs/pyannote/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/setup.py'"'"'; __file__='"'"'/private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-install-s6kkeeco/llvmlite_36cc4c0439d340db8c9680e60e2979f0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/ng/ttd_xd6x00zbn4fgcdlz27380000gn/T/pip-record-q29lze81/install-record.txt --single-version-externally-managed --compile --install-headers /Users/dominic/anaconda3/envs/pyannote/include/python3.8/llvmlite Check the logs for full command output.

failed

CondaEnvException: Pip failed
``` 
this is all of the info from the terminal that I get when I run `conda env create -f vtc.yml`, the environment still is created.

**Comment by MarvinLvn** [comment]
Ah, at least we found the bug! The very first strange output I can see is `Failed to build numba llvmlite`. 
It's very likely linked to this [MAC-specific issue](https://github.com/MarvinLvn/voice-type-classifier/issues/28) one of our users recently posted. 

Could you please try to:

1) Remove the conda env:

```
conda remove --name pyannote --all
```

2) Modify the 3rd line of `pyannote-audio/requirements.txt`:

The 3rd line should be `numba` instead of `numba==0.48.0  # TODO: remove once librosa 0.8 is out`

3) Re-install the env: 

```
conda env create -f vtc.yml
```

Let me know if this works, and I'll modify the `requirements.txt` to make sure future users won't encounter the same issue.

**Comment by shibess** [comment]
this worked! Thanks so much!

**Comment by MarvinLvn** [comment]
Glad your problem is solved!
