### ISSUE TITLE
ImportError: cannot import name 'Pretrained' from 'pyannote.audio.features

### ISSUE THREAD

**Issue by NoahBarker** [MarvinLvn/voice-type-classifier#31]
(pyannote) nb639@air116:/scratches/dialfs/child/splash/exp-nb639/voice_type_classifier$ ./apply.sh /scratches/dialfs/child/splash/exp-nb639/data/diarisation_training_data/uri/test/audio

Creating config for pyannote.

Done creating config for pyannote.

Feature extraction using pretrained models are not available because something went wrong at import: "cannot import name 'SafeFunction' from 'joblib._parallel_backends' (/scratches/dialfs/child/splash/exp-nb639/conda_environments/miniconda_pyth3.11/envs/pyannote/lib/python3.8/site-packages/joblib/_parallel_backends.py)".

Traceback (most recent call last):

  File "/scratches/dialfs/child/splash/exp-nb639/conda_environments/miniconda_pyth3.11/envs/pyannote/bin/pyannote-audio", line 8, in <module>

    sys.exit(main())

  File "/scratches/dialfs/child/splash/exp-nb639/conda_environments/miniconda_pyth3.11/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/applications/pyannote_audio.py", line 307, in main

    from .labels_detection import MultilabelDetection

  File "/scratches/dialfs/child/splash/exp-nb639/conda_environments/miniconda_pyth3.11/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/applications/labels_detection.py", line 39, in <module>

    from pyannote.audio.applications.base import create_zip

  File "/scratches/dialfs/child/splash/exp-nb639/conda_environments/miniconda_pyth3.11/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/applications/base.py", line 54, in <module>

    from pyannote.audio.features import Pretrained

ImportError: cannot import name 'Pretrained' from 'pyannote.audio.features' (/scratches/dialfs/child/splash/exp-nb639/conda_environments/miniconda_pyth3.11/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/features/__init__.py)

Something went wrong when applying the model

Aborting."

Hi,

I am getting this error while trying to apply the model to a folder of audio files, I have tried changing to various versions of pyannote.audio to no success. I created the environment using: 

"conda env create -f vtc.yml"

Thanks

**Comment by MarvinLvn** [comment]
Hi there,

Can you try to do: 

```
conda activate pyannote
pip install joblib==1.2.0
```
and let me know if this works? 

Cheers!

**Comment by NoahBarker** [comment]
This worked thank you!
